[tool.poetry]
name = "pe-org-air-platform"
version = "0.1.0"
description = "PE OrgAIR Platform Foundation - FastAPI service for company and assessment management"
authors = ["BigDataIA-Spring26-Team-1"]
readme = "README.md"
packages = [{ include = "app", from = "pe-org-air-platform" }]


[tool.poetry.dependencies]
python = "^3.12"
annotated-doc = "0.0.4"
annotated-types = "0.7.0"
anyio = "4.12.1"
asn1crypto = "1.5.1"
boto3 = "1.42.36"
botocore = "1.42.36"
certifi = "2026.1.4"
cffi = "2.0.0"
charset-normalizer = "3.4.4"
click = "8.3.1"
colorama = "0.4.6"
cryptography = "46.0.4"
fastapi = "0.128.0"
filelock = "3.20.3"
h11 = "0.16.0"
httpcore = "1.0.9"
httptools = "0.7.1"
httpx = "0.28.1"
idna = "3.11"
iniconfig = "2.3.0"
jmespath = "1.1.0"
packaging = "26.0"
platformdirs = "4.5.1"
pluggy = "1.6.0"
pycparser = "3.0"
pydantic = "2.12.5"
pydantic-settings = "2.12.0"
pydantic-core = "2.41.5"
pygments = "2.19.2"
pyjwt = "2.10.1"
pyopenssl = "25.3.0"
pytest = "9.0.2"
python-dateutil = "2.9.0.post0"
python-dotenv = "1.2.1"
pytz = "2025.2"
pyyaml = "6.0.3"
redis = "7.1.0"
requests = "2.32.5"
s3transfer = "0.16.0"
six = "1.17.0"
snowflake-connector-python = "4.2.0"
sortedcontainers = "2.4.0"
starlette = "0.50.0"
tomlkit = "0.14.0"
typing-inspection = "0.4.2"
typing-extensions = "4.15.0"
urllib3 = "2.6.3"
uvicorn = "0.40.0"
watchfiles = "1.1.1"
websockets = "16.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"